### ISSUE TITLE
The timeout is too short to execute 'generate' command

### ISSUE THREAD

**Issue by forchain** [HalalChain/qitmeer-cli#12]
~/github.com/HalalChain/qitmeer-cli(master*) » cli generate 16                                                                

getResString [miner_generate]: sendPostRequest: httpClient.Do err: Post https://127.0.0.1:18131: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

As we all know, mining is slow...

**Comment by 5dao** [comment]
rpc timeout default 30 second ,you can change if by --timeout

eg. --timeout=2m // 2minute

**Comment by forchain** [comment]
OK, accepted
