### ISSUE TITLE
go build failed 

### ISSUE THREAD

**Issue by blocklee** [HalalChain/qitmeer-cli#13]
- build时出现如图报错，该如何处理：

![cli](https://user-images.githubusercontent.com/32875657/60934348-77fa6b00-a2f8-11e9-81da-5a122ecc4c02.png)

在使用qx时，也出现类似的报错：

![qx](https://user-images.githubusercontent.com/32875657/60934442-d1fb3080-a2f8-11e9-97ed-48fc36ad1774.png)

**Comment by 5dao** [comment]
golang "GFW" problem,I would update go mod replace packge reference

**Comment by blocklee** [comment]
> golang "GFW" problem,I would update go mod replace packge reference

ok, waiting for your work.

**Comment by 5dao** [comment]
fix,please clone align
