### ISSUE TITLE
qx base58/base16转换错误

### ISSUE THREAD

**Issue by jack8086wang** [HalalChain/qitmeer-cli#21]
./qx base58-decode T为例，正确值应该是33，工具显示是1a
./qx base58-decode t为例，正确值应该是1b,工具显示33， 看起来大小位置弄反了，而且还错开一位

**Comment by dindinw** [comment]
@jack8086wang 
https://tools.ietf.org/id/draft-msporny-base58-01.html#alphabet
<img width="531" alt="Screen Shot 2020-10-07 at 7 47 53 AM" src="https://user-images.githubusercontent.com/1134993/95271846-8162e200-0871-11eb-90ed-dbf1b48ca86c.png">
T -> 26 (0x1a)
t -> 51 (0x33)
