### ISSUE TITLE
generate and tx command not working

### ISSUE THREAD

**Issue by forchain** [HalalChain/qitmeer-cli#4]
~/github.com/forchain/qitmeer-cli(master*) » ./qitmeer-cli tx ae22833ee61d67c9e0504852b55f22988af7e9d8284162fd4c5f47f85570f2a3
getResString [getRawTransaction]: sendPostRequest: resp.Error: {"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"invalid argument 0: hex string has length 0, want 64 for UnprefixedHash"}}
,sendData: {"jsonrpc":"1.0","method":"getRawTransaction","params":["",true],"id":1}

~/github.com/forchain/qitmeer-cli(master*) » ./qitmeer-cli generate 1                                                         Tony@Mac
getResString [generate]: sendPostRequest: resp.Error: {"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"The method generate does not exist/is not available"}}
,sendData: {"jsonrpc":"1.0","method":"generate","params":[1],"id":1}

**Comment by 5dao** [comment]
the problem may be  with qitmeer. ,"generate" method shoud be config in qitmeer lastest version,and "getRawTransaction" parameter tx is required

**Comment by forchain** [comment]
just verified the latest build, generate is still not working

**Comment by forchain** [comment]
@5dao , confirmed with @lochjin , this error should be regarding cli, please check with him

**Comment by lochjin** [comment]
> the problem may be with qitmeer. ,"generate" method shoud be config in qitmeer lastest version,and "getRawTransaction" parameter tx is required

When RPC calls, the method is prefixed with the module name. This has always been the case, but no one wants to add it.Everyone can only succeed because of just using the default module `nox`,  the server helps you do what you should do.  So the right thing to do is: `miner_generate`

**Comment by 5dao** [comment]
https://github.com/HalalChain/qitmeer-cli/pull/11

`--httpmodules=miner --httpmodules=nox
`
