### ISSUE TITLE
upgrade command line references for qitmeer-cli

### ISSUE THREAD

**Issue by dindinw** [HalalChain/qitmeer-cli#5]
- upgrade doc at https://halalchain.github.io/docs/en/qitmeer-cli/
- add usage & example for the following commands:
  - createrawtransaction
  - decoderawtransaction
  - generate 
  - getUtxo 
  - getblock 
  - getblockcount 
  - getblockhash 
  - getblocktemplate 
  - getmempool 
  - getrawtransaction
  - sendrawtransaction
  - txSign

**Comment by 5dao** [comment]
https://github.com/HalalChain/docs/pull/21
