### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by dindinw** [HalalChain/qitmeer-cli#8]
The latest code results in a build failure. 
- the master code has been rollbacked
- please fix build failure at wallet branch https://github.com/HalalChain/qitmeer-cli/tree/wallet
```
$ go build
can't load package: package github.com/HalalChain/qitmeer-cli: unknown import path "github.com/HalalChain/qitmeer-cli": cannot find module providing package github.com/HalalChain/qitmeer-cli
```

**Comment by 5dao** [comment]
the next commit will checkout new branch
