### ISSUE TITLE
help of createrawtransaction is not clear

### ISSUE THREAD

**Issue by forchain** [HalalChain/qitmeer-cli#9]
~/github.com/forchain/qitmeer-cli(master*) » ./qitmeer-cli createrawtransaction                                                                                             Tony@Mac
Error: requires at least 1 arg(s), only received 0
Usage:
  qitmeer-cli createrawtransaction {tx} [flags]

Aliases:
  createrawtransaction, createrawtx, createRawTransaction

Examples:

		createRawTransaction xx

what is the format of  tx, how to create a raw transaction

**Comment by 5dao** [comment]
fix
